 
   <?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
 
?>
 <!-- Cart -section - Start
        ================================================== -->
<section  data-block="minicart" class="minicart-wrapper" id="sidebarcart_custom">      
                                     
                                        <a class="action showcart active" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
                                           data-bind="scope: 'minicart_content'" hidden>
                                            <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
                                            <span class="counter qty empty cart-item-counter"
                                                  data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
                                                <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
                                                <span class="counter-label">
                                                <!-- ko if: getCartParam('summary_count') -->
                                                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                                                    <!-- ko i18n: 'items' --><!-- /ko -->
                                                <!-- /ko -->
                                                </span>
                                            </span>
                                        </a>
                                        <?php if ($block->getIsNeedToDisplaySideBar()) :?>
                                            <div class="block block-minicart"
                                                 data-role="dropdownDialog"
                                                 data-mage-init='{"dropdownDialog":{
                                                    "appendTo":"[data-block=minicart]",
                                                    "triggerTarget":".showcart",
                                                    "timeout": "2000",
                                                    "closeOnMouseLeave": false,
                                                    "closeOnEscape": true,
                                                    "triggerClass":"active",
                                                    "parentClass":"active",
                                                    "buttons":[]}}'>
                                                <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                                                    <!-- ko template: getTemplate() --><!-- /ko -->
                                                </div>
                                                <?= $block->getChildHtml('minicart.addons') ?>
                                            </div>
                                        <?php else :?>
                                            <script>
                                                require(['jquery'], function ($) {
                                                    $('a.action.showcart').click(function() {
                                                        $(document.body).trigger('processStart');
                                                    });
                                                });
                                            </script>
                                        <?php endif ?>
                                        <script>
                                            window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
                                        </script>
                                        <script type="text/x-magento-init">
                                        {
                                            "[data-block='minicart']": {
                                                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                                            },
                                            "*": {
                                                "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                                                    $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
                                                ) ?>"
                                            }
                                        }
                                        </script>

                                   
 
 
 
		<!-- <button class="close-btn"><i class="fa fa-times" aria-hidden="true"></i></button>		
			<h2>YOUR CART</h2>
		<hr>
		
		<div class="cartPro">
			<div class="thumb"><img src="assets/images/thumbnail/thumb-1.jpg" alt="thumbnail"></div>
			<div class="thumbText">
			<h3>IE MK6 GOLF R / MK5 GTI COLD AIR INTAKE KIT</h3>
			<h3>SKU: IEINCB4></h3>
			<h3>$665.00</h3>			
			<ul class="quant">
			<li class="dicrease"><a href="">-</a></li>
			<li class="numb">1</li>
			<li class="increase"><a href="">+</a></li>
			<li class="remove"><a href="">Remove</a></li>
			</ul>
			</div> 
		</div>
		
		<div class="cartPro last">
			<div class="thumb"><img src="assets/images/thumbnail/thumb-1.jpg" alt="thumbnail"></div>
			<div class="thumbText">
			<h3>IE MK6 GOLF R / MK5 GTI COLD AIR INTAKE KIT</h3>
			<h3>SKU: IEINCB4></h3>
			<h3>$665.00</h3>			
			<ul class="quant">
			<li class="dicrease"><a href="">-</a></li>
			<li class="numb">1</li>
			<li class="increase"><a href="">+</a></li>
			<li class="remove"><a href="">Remove</a></li>
			</ul>
			</div>
		</div>
		
		
		<div class="total">
			<h3>Total <span> $734.95 AUD </span></h3>
		</div>
		
		<button class="checkout">Checkout</button> -->
		
        </section>
<!-- Cart -section - End
        ================================================== -->
        

 