<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>


<li class="custom-col here i am">
    <div class="newsletter-content mb-30">
        <h3 class="footer-title-text mb-30">Subscribe Our Newsletter</h3>
        <div class="block newsletter">
         <!-- <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div> -->
        <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control form-item">
                    <label for="newsletter">
                       <?php /* <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        */?>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter Your Email ID')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary custom-btn bg-default-yellow"
                        title="<?= $block->escapeHtmlAttr(__('Submit Now')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Submit Now')) ?></span>
                </button>
            </div>
        </form>
    </div>
 
     

    <div class="follow-us ul-li clearfix">
        <h3 class="footer-title-text mb-30">Follow Us On</h3>
        <ul class="clearfix">
            <li><a href="#!"><i class="fab fa-facebook-f"></i></a></li>
            <li><a href="#!"><i class="fab fa-twitter"></i></a></li>
            <li><a href="#!"><i class="fab fa-instagram"></i></a></li>
        </ul>
    </div>
</li>

</ul>
 
