<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
 
?>
<div class="col-sm-2 col-md-2 col-lg-2 col-2 tes_custom" id="header_cartsection">
							<div class="btns-group ul-li-right clearfix">


                            <ul class="clearfix">
								<li>
										<a href="#" class="item-btn" id="account_home">
											<img src="<?php echo $block->getBaseurl()."/pub/media/assets/images/icons/icon_3.png"?>" alt="icon_not_found">
                                        </a>
                                        <div id="my_account_drop" class="my_account">
                                        <ul>
                                       <li><a href="<?php echo $block->getBaseUrl().'customer/account/'?>" class="md-opjjpmhoiojifppkkcdabiobhakljdgm_doc">Dashboard</a></li>
                                       <li><a href="<?php echo $block->getBaseUrl().'sales/order/history/'?>" class="md-opjjpmhoiojifppkkcdabiobhakljdgm_doc">Orders</a></li>
                                       <!-- <li><a href="<?php //echo $block->getBaseUrl().'customer/account/'?>" class="md-opjjpmhoiojifppkkcdabiobhakljdgm_doc">Favourites</a></li>
                                      <li> -->
                                      <li>
                                    <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                    $customerSession = $objectManager->get('Magento\Customer\Model\Session');

                                     if($customerSession->isLoggedIn()) {?>
                                     <a href="<?php echo $block->getBaseUrl().'customer/account/logout/'?>" class="md-opjjpmhoiojifppkkcdabiobhakljdgm_doc">Log Out</a>
                                    <?php 
                                     }
                                    else
                                    {?>
                                    <a href="<?php echo $block->getBaseUrl().'customer/account'?>" class="md-opjjpmhoiojifppkkcdabiobhakljdgm_doc">Log In</a>
                                    <?php
                                    }?>                                      
                                    </li>
                                       </ul>
                                        </div>
									</li>
								<li>
										<a href="#!" class="item-btn">
											<img src="<?php echo $block->getBaseurl()."pub/media/assets/images/icons/icon-4.png"?>" alt="icon_not_found">											
										</a>
										<div class="cart-item-counter">6</div>
								</li>
									<li>

                                    <div data-block="minicart" class="minicart-wrapper">
                                        
    <a class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter qty empty cart-item-counter"
              data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()) :?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else :?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
    
</div>
									 
									</li>									
								</ul>

                            </div>
</div>

 