<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
 
<h3 class="title-text mb-0">Safe and Secure Shopping</h3>
<span class="payment-card">
<img src="<?php echo $block->getBaseUrl().'pub/media/assets/images/payment_card.png'?>" alt="imahe_not_found">
</span>
<p class="copyright-text mb-0"><?= $block->escapeHtml($block->getCopyright()) ?></p>
 
 
