<li class="level0 nav-5 level-top parent">
    <a href="/contact.html" class="level-top"><span>CONTACT US</span></a>
    <!-- YOUR SUBMENU -->
    <ul class="level0 submenu">
        <li class="level1 nav-5-1 first">
            <a href="/shoes/high-heels.html"><span>Bookings</span></a>
        </li>

        <li class="level1 nav-5-1 second">
            <a href="/shoes/high-heels.html"><span>Spare Parts Enquiry</span></a>
        </li>


        <li class="level1 nav-5-1 last">
            <a href="/shoes/high-heels.html"><span>Apply To Become A Dealer</span></a>
        </li>
    </ul>
</li>

 