<?php


/**
 * @var \Smart\Vwcentral\Block\Featured $block
 */

$collection = $block->getFeaturedCollection();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_helper = $objectManager->get('Smart\Vwcentral\Helper\Data');
$imageHelper = $objectManager->create('Magento\Catalog\Helper\Image');
$currencyInterface = $objectManager->get('Magento\Framework\Pricing\PriceCurrencyInterface');

?>
<section class="product-section featured-product-section clearfix">
    <div class="container">

        <div class="section-title text-center mb-30">
            <h2 class="title-text mb-0">Featured Products</h2>
        </div>

        <div class="row">
            <?php foreach ($collection as $_product) { ?>
                <div class="col-lg-3 col-md-6 col-sm-12 custom-col">
                    <div class="product-item item">
                        <div class="loader"></div>
                        <div class="item-image image-container">
                            <a href="<?php echo $_product->getProductUrl() ?>" class="item-link">
                                <img src="<?php echo $block->getImageUrl($_product, 'product_page_image_large') ?>" alt="imahe_not_found">
                            </a>
                        </div>
                        <div class="item-content clearfix">


                            <div class="item-brand mb-30 clearfix">
                                <span class="item-code float-left">SKU: <?php echo $_product->getSku() ?></span>
                                <?php
                                $id_brand = $_product->getData('manufacturer');
                                $categoryIds = $_product->getCategoryIds();
                                $cat_name = $_product->getAttributeText('manufacturer');
                                $cat_url = $_helper->getbrand($cat_name, $categoryIds);
                                if ($cat_url != 'empty') {
                                ?>

                                    <a href="#!" class="brand-logo float-right">


                                        <img src="<?php echo $cat_url; ?>" alt="logo_not_found">

                                    </a>
                                <?php } ?>
                            </div>
                            <h3 class="item-title mb-15">
                                <a href="<?php echo $_product->getProductUrl() ?>" class="title-link">
                                    <?php echo $_product->getName(); ?>
                                </a>
                            </h3>
                            <div class="item-price mb-15">
                                <!-- <del>$80.15</del> <span>$55.00</span> -->
                                <?php if ($_product->getSpecialPrice() == $_product->getFinalPrice()) { ?>
                                    <del><?php echo $currencyInterface->format(
                                                $_product->getPrice(), // the price value.
                                                false,                // don't include the container span.
                                                2                     // default precision is two decimals, but I want 4 for some reason.
                                            );  ?></del>
                                    <span><?php echo $currencyInterface->format(
                                                $_product->getSpecialPrice(), // the price value.
                                                false,                // don't include the container span.
                                                2                     // default precision is two decimals, but I want 4 for some reason.
                                            );  ?> </span>
                                <?php } else { ?>
                                    <span><?php echo $currencyInterface->format(
                                                $_product->getPrice(), // the price value.
                                                false,                // don't include the container span.
                                                2                     // default precision is two decimals, but I want 4 for some reason.
                                            );  ?></span>
                                <?php } ?>
                            </div>

                            <div class="btns-group ul-li-block clearfix">
                                <ul class="clearfix">
                                    <?php if ($block->getCompatible($_product->getId())) {
                                    ?>
                                        <li><a href="#!" class="bg-default-black">Compatible</a></li>
                                    <?php } ?>
                                    <?php

                                    if ($_product->isSaleable()) : ?>

                                        <form class="addcarslider" action="<?php echo $block->getAddUrl($_product) ?>" method="post">
                                            <input type="hidden" name="product" value="1" tabindex="0">
                                            <input name="form_key" type="hidden" value="[form_key]" tabindex="0">
                                            <input name="is_ajax" type="hidden" value="1" tabindex="0">
                                            <button class="action tocart primary slider_addcart" type="submit" title="Add to Cart" tabindex="0">
                                                <span>Add to Cart</span>
                                            </button>
                                        </form>

                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>



        </div>

    </div>
</section>