<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<!-- advertisement-section - start
		================================================== -->
<section id="advertisement-section" class="advertisement-section bg-light-gray sec-ptb-60 clearfix">
	<div class="container">

		<div class="finding-form">
			<h3 class="title-text mb-15">Find Parts By Vehicle</h3>
			<form action="#" class="garage">
				<div class="select-options-list ul-li clearfix">
					<ul class="clearfix">
						<li>
							<div class="select-option">
								<select class="sel_make">
									<option data-display="Select Make">Nothing</option>

								</select>
							</div>

						</li>
						<li>
							<div class="select-option">
								<select class="sel_model">
									<option data-display="Select Model">Nothing</option>

								</select>
							</div>
						</li>
						<li>
							<div class="select-option">
								<select class="sel_gen">
									<option data-display="Select Generation">Nothing</option>
								</select>
							</div>
						</li>
						<li>
							<div class="select-option">
								<select class="sel_sub">
									<option data-display="Select Sub Models">Nothing</option>
								</select>
							</div>
						</li>
					</ul>
				</div>
				<button id="slider_garage" type="submit" class="addtogarage custom-btn yellowBtn">Add To Garage</button>
			</form>
		</div>

		<div class="row">
			<div class="col-lg-4 col-md-4 col-sm-12">
				<div class="advertisement-item">
					<a href="#!" class="advertisement-link">
						<img src="<?php echo $url . 'assets/images/advertisement/WEBSITE-PROMO1.png' ?>" alt="imahe_not_found">
					</a>
				</div>
			</div>

			<div class="col-lg-4 col-md-4 col-sm-12">
				<div class="advertisement-item">
					<a href="#!" class="advertisement-link">
						<img src="<?php echo $url . 'assets/images/advertisement/WEBSITE-PROMO1.png'; ?>" alt="imahe_not_found">
					</a>
				</div>
			</div>

			<div class="col-lg-4 col-md-4 col-sm-12">
				<div class="advertisement-item">
					<a href="#!" class="advertisement-link">
						<img src="<?php echo $url . 'assets/images/advertisement/WEBSITE-PROMO1.png' ?>" alt="imahe_not_found">
					</a>
				</div>
			</div>
		</div>

	</div>
</section>
<!-- advertisement-section - end
		================================================== -->

 