
<?php 
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 
 $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 $url=$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<!-- advertisement-section - start
		================================================== -->
		<section id="advertisement-section" class="advertisement-section bg-light-gray sec-ptb-60 clearfix">
			<div class="container">

				<div class="finding-form">
					<h3 class="title-text mb-15">Find Parts By Vehicle</h3>
					<form action="#">
						<div class="select-options-list ul-li clearfix">
							<ul class="clearfix">
								<li>
									<div class="select-option">
										<select id="sel_make">
											<option data-display="Select Make">Nothing</option>
											 
										</select>
                                    </div>
                                   
								</li>
								<li>
									<div class="select-option">
										<select id="sel_model">
											<option data-display="Select Model">Nothing</option>
										 
										</select>
									</div>
								</li>
								<li>
									<div class="select-option">
										<select id="sel_gen">
											<option data-display="Select Generation">Nothing</option>											 
										</select>
									</div>
								</li>
								<li>
									<div class="select-option">
										<select id="sel_sub">
											<option data-display="Select Sub Models">Nothing</option>											 
										</select>
									</div>
								</li>
							</ul>
						</div>
					</form>
				</div>

				<div class="row">
					<div class="col-lg-4 col-md-4 col-sm-12">
						<div class="advertisement-item">
							<a href="#!" class="advertisement-link">
								<img src="<?php echo $url.'assets/images/advertisement/WEBSITE-PROMO1.png'?>" alt="imahe_not_found">
							</a>
						</div>
					</div>

					<div class="col-lg-4 col-md-4 col-sm-12">
						<div class="advertisement-item">
							<a href="#!" class="advertisement-link">
								<img src="<?php echo $url.'assets/images/advertisement/WEBSITE-PROMO1.png';?>" alt="imahe_not_found">
							</a>
						</div>
					</div>

					<div class="col-lg-4 col-md-4 col-sm-12">
						<div class="advertisement-item">
							<a href="#!" class="advertisement-link">
								<img src="<?php echo $url.'assets/images/advertisement/WEBSITE-PROMO1.png'?>" alt="imahe_not_found">
							</a>
						</div>
					</div>
				</div>
				
			</div>
		</section>
		<!-- advertisement-section - end
		================================================== -->

        <script>
require([
    'jquery',
    'owlcrousel'  // the alias for "mage/accordion"
], function ($) {
    $(function () { // to ensure that code evaluates on page load
       /* MAIN CROUSEL eND */
       $( document ).ready(function() {       

                     
		getcat('sel_make',5)
		 
           function getcat(element,catid)
           {
            var partfinderurl='http://127.0.0.1/vwcentral/wwcentral/ajax/partfinder';           
			var data={id:catid};
			 
			if(catid!=-1 && (catid>0))
			{
				a 
			   $.ajax({
                url : partfinderurl,
                dataType : 'json',
                type : 'POST',
                data: data,
                 success : function(response)
                 {                
                    var len = response.length;
                    $("#"+element).empty();                  
                    $("#"+element).append('<option value="-1" data-display="Select Make">Nothing</option>');
                    for( var i = 0; i<len; i++){
                    var id = response[i]['value'];
                    var name = response[i]['name'];
                    var dred = response[i]['dataredirect'];
					$("#"+element).append("<option value='"+id+"' data-redirect='"+dred+"'>"+name+"</option>");
					
				}   
				//$("#"+element).niceSelect();                                 
               // $("#"+element).addClass('nice-select');                
                 },
                 error : function(response)
                 {              
				
					reset(element)
                 
                 }
			 });
			}
			else
			{
				reset(element)
			}

			
			 
		   }
		   

		   function reset(element)
		   {
			if(element=='sel_make')
				{		 
				 
					$("#sel_model").empty();  	
					$("#sel_model").append('<option value="-1" data-display="Select Make">Nothing</option>'); 
					$("#sel_gen").empty();  
					$("#sel_gen").append('<option value="-1" data-display="Select Make">Nothing</option>');
					$("#sel_sub").empty();  
					$("#sel_sub").append('<option value="-1" data-display="Select Make">Nothing</option>');
									

				}	
				else if(element=='sel_model')
				{
					
				 
					$("#sel_gen").empty();  
					$("#sel_gen").append('<option value="-1" data-display="Select Make">Nothing</option>');
					$("#sel_sub").empty();  
					$("#sel_sub").append('<option value="-1" data-display="Select Make">Nothing</option>');	
				}
				else if(element=='sel_gen')
				{ 
					$("#sel_sub").empty();  
					$("#sel_sub").append('<option value="-1" data-display="Select Make">Nothing</option>');
					 
				}
				else
				{
					//
				}
		   }
       
        $("#sel_make").change(function(){


			var catid = $(this).val();
			if(catid)
			{			 
            var eleid='sel_model';
			getcat(eleid,catid);
			} 
			
			
           // alert(catid);               
        });

        $("#sel_model").change(function(){
			var catid = $(this).val();		 
            var eleid='sel_gen';
			getcat(eleid,catid);
		 
			 
           // alert(catid);               
        });

        $("#sel_gen").change(function(){
			var catid = $(this).val();			            
            var eleid='sel_sub';
			getcat(eleid,catid);
			 
           // alert(catid);               
        });
        

    
         
  });
  // product carousel - end
  // 
    });
});
</script>