<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>

<ol class="items checkItem">
    <?php foreach ($filterItems as $filterItem) : ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0) : ?>
               
                <label class="inCheck" > 
			    <input type="checkbox" class="filter_add">  <?= /* @noEscape */ $filterItem->getLabel() ?><span class="checkmark"></span>
                 </label>        
        
                 <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>" style="display:none !important">
                    <?= /* @noEscape */ $filterItem->getLabel() ?>
                    <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                        <span class="count"><?= /* @noEscape */ (int)$filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1) :
                                ?> <?= $block->escapeHtml(__('item')) ?><?php
                            else :
                                ?> <?= $block->escapeHtml(__('item')) ?><?php
                            endif;?></span></span>
                    <?php endif; ?>
                </a>
     
            <?php else :?>
                <?= /* @noEscape */ $filterItem->getLabel() ?>
                <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                    <span class="count"><?= /* @noEscape */ (int)$filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1) :
                            ?><?= $block->escapeHtml(__('items')) ?><?php
                        else :
                            ?><?= $block->escapeHtml(__('items')) ?><?php
                        endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
<script>
require(['jquery'], function($){
$('.filter_add').on('click', function(event) {  
    var item=$(this); 
    if(item.is(":checked"))
    {
     
       $(this).closest('li').find('a').trigger('click');
    }
     
     
  });
});
</script>