<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php

/* logic for the compatible non copatible products*/


$_productCollection = $block->getLoadedProductCollection();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_helper = $objectManager->get('Smart\Vwcentral\Helper\Data');


?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else : ?>
    <div id="toolbar_top">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?= $block->getAdditionalHtml() ?>

    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $classes = " col-lg-4 col-md-6 col-sm-12 custom-col";
    } else {
        $viewMode = 'list';

        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $classes = "col-lg-12 col-md-12 col-sm-12 custom-col";
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items product-section clearfix">
            <div class="row">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product) : ?>
                    <li class="item product <?php echo $classes; ?>">
                        <div class="product-item">

                            <?php

                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $helperImport = $objectManager->get('\Magento\Catalog\Helper\Image');
                            $imageUrl = $helperImport->init($_product, 'product_page_image_small')
                                ->setImageFile($_product->getSmallImage()) // image,small_image,thumbnail
                                ->resize(380)
                                ->getUrl();

                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);


                            ?>


                            <div class="item-image image-container">
                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="item-link">
                                    <img src="<?php echo $imageUrl; ?>" alt="imahe_not_found">
                                </a>
                            </div>
                            <div class="item-content clearfix">
                                <div class="item-brand mb-30 clearfix">
                                    <span class="item-code float-left">SKU:<?php echo $_product->getSku(); ?></span>

                                    <?php
                                    //$id_brand = $_product->getData('manufacturer');
                                    $categoryIds = $_product->getCategoryIds();
                                    $product = $objectManager->get('Magento\Catalog\Model\Product')->load($_product->getId());
                                    $cat_name = $product->getAttributeText('manufacturer');
                                    $cat_url = $_helper->getbrand($cat_name, $categoryIds);

                                    if ($cat_url != 'empty') {
                                    ?>

                                        <a href="#!" class="brand-logo float-right">


                                            <img src="<?php echo $cat_url; ?>" alt="logo_not_found">

                                        </a>
                                    <?php } ?>




                                    <!-- <a href="#!" class="brand-logo float-right">
                                        <img src="<?php //echo $block->getBaseUrl() . 'pub/media/assets/images/product_brand/img_1.png' ?>" alt="logo_not_found">
                                    </a> -->
                                </div>
                                <h3 class="item-title mb-15">
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="title-link">
                                        <?php echo $_productNameStripped; ?>
                                    </a>
                                </h3>
                                <!-- <div class="item-price mb-15">
									<del>$80.15</del> <span>$55.00</span>
                                </div> -->
                                <div class="item-price mb-15">
                                    <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                </div>

                                <div class="btns-group ul-li-block clearfix">
                                    <ul class="clearfix">


                                        <?php
                                        if ($block->getSelected()) {
                                            if ($block->getCompatible($_product->getId())) { ?>
                                                <li><a href="#!" class="bg-default-black">Compatible</a></li>
                                            <?php } else { ?>
                                                <li><a href="#!" class="bg-default-black">Non Compatible</a></li>
                                            <?php }
                                        } else {
                                            ?>

                                        <?php  } ?>

                                        <li>
                                            <div class="product actions product-item-actions" <?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                <div class="actions-primary" <?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                    <?php if ($_product->isSaleable()) : ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <input name="is_ajax" type="hidden" value="2">
                                                            <?php
                                                            if ($_product->getTypeId() != 'configurable') { ?>
                                                                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart primary">
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            <?php } ?>
                                                        </form>
                                                    <?php else : ?>
                                                        <?php if ($_product->isAvailable()) : ?>
                                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                        <?php else : ?>
                                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
                <row>
        </ol>
    </div>
    <div id="toolbar_bottom">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>