<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt()
?>

 
				<div class="container">			 


                    <div class="row">
<div class="col-4">
<ul class="navIcon">
	<li><span data-action="toggle-nav" class="action nav-toggle"><span><?= $block->escapeHtml(__('Toggle Nav')) ?></span></span></li>
	<li class="main_search_mobhead"><a href="#" id="mobsearch"><img src="<?php echo $block->getBaseUrl().'pub/media/assets/images/search.png'?>" alt="menuIcon"></a>
</li>
</ul>
</div>

<div class="col-3"><a href="<?php echo $block->getBaseUrl('/')?>" class="logoHead"><img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>" alt="logo"></a></div>



    <?php /*
<div class="col-3">
<span data-action="toggle-nav" class="action nav-toggle"><span><?= $block->escapeHtml(__('Toggle Nav')) ?></span></span>
<div class="brand-logo clearfix">
<a id="wc_alogo"    class="logo brand-link float-left"
    href="<?= $block->escapeUrl($block->getUrl('')) ?>"
    title="<?= $block->escapeHtmlAttr($storeName) ?>"
    aria-label="store logo">
    <img id="logo_wc" src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $block->getLogoWidth() ? 'width="' . $block->escapeHtmlAttr($block->getLogoWidth()) . '"' : '' ?>
            <?= $block->getLogoHeight() ? 'height="' . $block->escapeHtmlAttr($block->getLogoHeight()) . '"' : '' ?>
    />
</a>
</div>
</div> */
